DATABASE_USER = 'stats_user'
DATABASE_PASSWORD = 'vV775533Vv'
DATABASE_PORT = 3306
DATABASE_NAME = 'stats_db'

DB_CONFIG = {
    'database': DATABASE_NAME,
    'password': DATABASE_PASSWORD,
    'user': DATABASE_USER,
    'port': DATABASE_PORT
}

